services:
  managed_node:
     image: mms-automation-agent:local
     ports:
       - "27017-28017:27017"
     networks:
       - ops-manager
     environment:
       - mmsGroupId= #<Project ID>
       - mmsApiKey=  #<API key>
       - mmsBaseUrl=http://ops-manager:8080
       - logFile=/data/logs/automation-agent.log
       - logLevel=INFO

networks:
  ops-manager:
    name: opsmanager_network
    external: true